### ISSUE TITLE
Вопрос :)

### ISSUE THREAD

**Issue by kellolo** [antokhio/strapi-plugin-categorizer#6]
Приветствую! Сейчас уже несколько дней ипусь с чем-то, что очень напоминает данный реп. Я правильно понял, что это способ реализовать фильтр значений из связанных полей?

У нас коллекции:
props <--- category ---> product ---> offer

в offer есть связь с props (one-to-many) и в выпадайку валит вообще все пропсы, а не те, которые должны быть в соотв. категории.

Это вот оно, да? :)

**Comment by antokhio** [comment]
Типа того... эта штука что бы строить древовидные структуры с селектором по каждому уровню
