### ISSUE TITLE
About strapi-plugin-categorizer@2.0.9 Compatibility issues with the Node.js version of plugins

### ISSUE THREAD

**Issue by bestXie** [antokhio/strapi-plugin-categorizer#9]
Hello!

I am trying to install it strapi-plugin-categorizer@2.0.9 The plugin encountered the following error:

`yarn add strapi-plugin-categorizer 
yarn add v1.22.22
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error strapi-plugin-categorizer@2.0.9: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.16.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

According to the error message, it seems that this plugin does not support Node.js 20.16.0, and the required version is>=14.19.1<=18. x.x. Is there a plan to update plugins to support version 20. x.x of Node.js? If not, is there a recommended solution so that I can use the plugin on the current version of Node.js?

Thank you for your help!

**Comment by antokhio** [comment]
https://github.com/antokhio/strapi-plugin-categorizer/pull/10

hi, just published ver 2.0.10
